_wandb:
    value:
        cli_version: 0.24.0
        e:
            7leiliz7jqincuyo9uavix5d8sac5usc:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "6442450944"
                args:
                    - --n-trials
                    - "10"
                    - --study-name
                    - cnn_lstm_hyperopt
                    - --storage
                    - sqlite:///optuna_study.db
                    - --pruning
                    - --use-wandb
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "494353338368"
                        used: "475499986944"
                email: alex.olson@outlook.com
                executable: /Users/alex/repos/piv-bubble-prediction/.venv/bin/python3
                host: Alexs-Macbook-7.local
                memory:
                    total: "25769803776"
                os: macOS-26.3-arm64-arm-64bit
                program: -m src.tune
                python: CPython 3.11.13
                root: /Users/alex/repos/piv-bubble-prediction
                startedAt: "2026-01-15T21:30:31.286310Z"
                writerId: 7leiliz7jqincuyo9uavix5d8sac5usc
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 35
            "2":
                - 1
                - 35
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
augment:
    value: false
device:
    value: null
direction:
    value: minimize
epochs:
    value: 50
force_cpu:
    value: false
limit:
    value: null
n_trials:
    value: 10
noise_std:
    value: 0.01
objective:
    value: validation_loss
output_dir:
    value: optuna_studies
patience:
    value: 10
pruning:
    value: true
sequence_length:
    value: 20
storage:
    value: sqlite:///optuna_study.db
stride:
    value: 1
study_name:
    value: cnn_lstm_hyperopt
temporal_shift_max:
    value: 2
test_split:
    value: 0.2
use_wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: piv-bubble-prediction
zarr_path:
    value: data/raw/all_experiments.zarr
